version: '2.4'

services:
    jekyll:
        image: jekyll/jekyll
        volumes:
            - .:/site
        command: bash -c "
            rm -f Gemfile.lock
            && bundle clean --force
            && bundler exec jekyll serve --watch --port=4000 --host=0.0.0.0 --livereload --verbose"
        ports:
            - '80:4000'